import {useEffect,useMemo,useRef,useState} from 'react'
import type {BlueprintSettings,Project} from './types'
import {generateCompactBlueprint,generateEasyBlueprint,maxPolyphony,type BlueprintCell,type BlueprintInstrument,type BlueprintPlan} from './blueprint'
import {exportBlueprint,exportBlueprintLayers} from './blueprintExport'
import {playProject,previewTone,stopPlayback} from './audio'
import './blueprint.css'

type Props={project:Project;instruments:readonly BlueprintInstrument[];language:string;onBack:()=>void;onSettingsChange:(settings:BlueprintSettings)=>void}
type PinchState={distance:number;zoom:number;anchorX:number;anchorY:number}
const canSelectPlaybackStart=(item:BlueprintCell)=>item.type==='source'||item.type==='repeater'
const textureFiles:Record<string,string>={earth:'grass_block_side.png',wood:'oak_planks.png',stone:'cobblestone.png',sand:'sand.png',glass:'glass.png',wool:'pink_wool.png',clay:'clay.png',gold:'gold_block.png',ice:'ice.png',bone:'bone_block_side.png',iron:'iron_block.png',soul:'soul_sand.png',pumpkin:'pumpkin_side.png',emerald:'emerald_block.png',hay:'hay_block_side.png',glow:'glowstone.png',copper:'copper_block.png','copper-exposed':'exposed_copper.png','copper-weathered':'weathered_copper.png','copper-oxidized':'oxidized_copper.png'}

export default function BlueprintView({project,instruments,language,onBack,onSettingsChange}:Props){
  const saved=project.blueprint??{runLength:40,compactSize:50,fold:'right' as const,includeSilentEdges:true}
  const [kind,setKind]=useState<'easy'|'packed'|'fishbone'>('easy'),[runLength,setRunLength]=useState(saved.runLength),[compactSize,setCompactSize]=useState(saved.compactSize??50)
  const [fold,setFold]=useState(saved.fold),[includeSilentEdges,setIncludeSilentEdges]=useState(saved.includeSilentEdges),[theme,setTheme]=useState<'dark'|'light'>(saved.theme??'dark')
  const [layerIndex,setLayerIndex]=useState(0),[showOptions,setShowOptions]=useState(false),[showExport,setShowExport]=useState(false),[showLegend,setShowLegend]=useState(false)
  const [selected,setSelected]=useState<string|null>(null),[startStep,setStartStep]=useState<number|null>(null),[playingStep,setPlayingStep]=useState(-1),[previewCell,setPreviewCell]=useState<string|null>(null),[particles,setParticles]=useState<number[]>([])
  const poly=maxPolyphony(project),ja=language==='ja',eligible=kind==='easy'?poly<=3:kind==='packed'?poly<=6:false
  const easy=useMemo(()=>poly<=3?generateEasyBlueprint(project,instruments,runLength,fold,includeSilentEdges):null,[project,instruments,runLength,fold,includeSilentEdges,poly])
  const compact=useMemo(()=>poly<=6?generateCompactBlueprint(project,instruments,compactSize,includeSilentEdges):null,[project,instruments,compactSize,includeSilentEdges,poly])
  const plan:BlueprintPlan|null=kind==='easy'?easy:kind==='packed'?(compact?.layers[Math.min(layerIndex,(compact?.layers.length??1)-1)]??null):null
  const wrapRef=useRef<HTMLElement>(null),shellRef=useRef<HTMLDivElement>(null),stageRef=useRef<HTMLDivElement>(null),zoomRef=useRef(1),playingRef=useRef(false),holdRef=useRef<number[]>([]),suppressClickRef=useRef(0),dragRef=useRef<{id:number;x:number;y:number;ox:number;oy:number;moved:boolean}|null>(null),pointsRef=useRef(new Map<number,{x:number;y:number;ox:number;oy:number}>()),pinchRef=useRef<PinchState|null>(null),pinchFrameRef=useRef<number|null>(null)
  const cell=40,axis=42
  const usedBlocks=useMemo(()=>{const plans=kind==='packed'&&compact?compact.layers:plan?[plan]:[];const seen=new Set<string>();return plans.flatMap(value=>value.cells).flatMap(item=>{if(item.type!=='note'||!item.texture||seen.has(item.texture))return[];seen.add(item.texture);const instrument=instruments.find(value=>value.texture===item.texture);return[{texture:item.texture,label:item.label??'0',name:instrument?(ja?instrument.blockJa:instrument.blockEn):item.texture}]})},[kind,compact,plan,instruments,ja])
  const save=(next:Partial<BlueprintSettings>)=>onSettingsChange({runLength,compactSize,fold,includeSilentEdges,theme,...next})
  const changeSize=(delta:number)=>{if(kind==='packed')setCompactSize(current=>{const next=Math.max(16,Math.min(96,current+delta));setLayerIndex(0);save({compactSize:next});return next});else setRunLength(current=>{const next=Math.max(8,Math.min(128,current+delta));save({runLength:next});return next})}
  const stopHold=()=>{holdRef.current.forEach(clearTimeout);holdRef.current=[]}
  const startHold=(delta:number,e:React.PointerEvent)=>{e.preventDefault();stopHold();changeSize(delta);holdRef.current=[window.setTimeout(()=>holdRef.current.push(window.setInterval(()=>changeSize(delta),125)),450)]}
  const cancelPinchFrame=()=>{if(pinchFrameRef.current!==null){window.cancelAnimationFrame(pinchFrameRef.current);pinchFrameRef.current=null}}
  const setZoom=(next:number,cx?:number,cy?:number)=>{if(!plan||!wrapRef.current||!shellRef.current||!stageRef.current)return;const wrap=wrapRef.current,old=zoomRef.current,value=Math.max(.35,Math.min(2.4,next)),x=cx??wrap.clientWidth/2,y=cy??wrap.clientHeight/2,ax=(wrap.scrollLeft+x)/old,ay=(wrap.scrollTop+y)/old;zoomRef.current=value;shellRef.current.style.transform=`scale(${value})`;stageRef.current.style.width=`${(axis*2+plan.width*cell)*value}px`;stageRef.current.style.height=`${(axis*2+plan.height*cell)*value}px`;wrap.scrollLeft=ax*value-x;wrap.scrollTop=ay*value-y}
  useEffect(()=>{if(plan)setZoom(zoomRef.current)},[plan?.width,plan?.height,layerIndex])
  useEffect(()=>{const timer=window.setTimeout(()=>{if(wrapRef.current){wrapRef.current.scrollLeft=0;wrapRef.current.scrollTop=wrapRef.current.scrollHeight}},60);return()=>clearTimeout(timer)},[kind,layerIndex])
  useEffect(()=>()=>{playingRef.current=false;stopPlayback();stopHold();cancelPinchFrame()},[])
  const choose=(item:BlueprintCell)=>{const key=item.groupId??`${item.x}-${item.y}`;if(item.type==='note'){void previewTone(Number(item.label),item.volume??1,item.instrument??'Harp');setPreviewCell(`${item.x}-${item.y}`);setTimeout(()=>setPreviewCell(null),260);return}if(!canSelectPlaybackStart(item))return;if(selected===key){setSelected(null);setStartStep(null)}else{setSelected(key);setStartStep(item.step??plan?.firstStep??0)}}
  const stopBlueprintPlayback=()=>{playingRef.current=false;stopPlayback();setPlayingStep(-1)}
  const play=async()=>{if(playingRef.current){stopBlueprintPlayback();return}if(!plan)return;stopPlayback();playingRef.current=true;const from=startStep??plan.firstStep,to=kind==='packed'?(compact?.lastStep??plan.lastStep):plan.lastStep;setPlayingStep(from);try{await playProject(project,from,step=>{if(!playingRef.current)return;if(step<0){playingRef.current=false;setPlayingStep(-1);return}setPlayingStep(step);setParticles(old=>[...old,step]);setTimeout(()=>setParticles(old=>old.filter(value=>value!==step)),250)},{usePan:false,toStep:to})}catch(error){if(playingRef.current){playingRef.current=false;setPlayingStep(-1)}console.error('Blueprint playback failed.',error)}}
  const cue=()=>{stopBlueprintPlayback();const source=plan?.cells.find(item=>item.type==='source')??plan?.cells.find(item=>item.type==='repeater');if(source){setSelected(source.groupId??`${source.x}-${source.y}`);setStartStep(source.step??plan?.firstStep??0)}}
  const pointerDown=(e:React.PointerEvent<HTMLElement>)=>{if(e.pointerType!=='touch')return;pointsRef.current.set(e.pointerId,{x:e.clientX,y:e.clientY,ox:e.clientX,oy:e.clientY});e.currentTarget.setPointerCapture(e.pointerId);if(pointsRef.current.size===1)dragRef.current={id:e.pointerId,x:e.clientX,y:e.clientY,ox:e.clientX,oy:e.clientY,moved:false};else{const[a,b]=[...pointsRef.current.values()],shell=shellRef.current;if(shell){const zoom=zoomRef.current,mx=(a.x+b.x)/2,my=(a.y+b.y)/2,rect=shell.getBoundingClientRect();pinchRef.current={distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),zoom,anchorX:(mx-rect.left)/zoom,anchorY:(my-rect.top)/zoom}}dragRef.current=null}e.preventDefault()}
  const pointerMove=(e:React.PointerEvent<HTMLElement>)=>{const point=pointsRef.current.get(e.pointerId);if(!point||!wrapRef.current)return;point.x=e.clientX;point.y=e.clientY;if(pointsRef.current.size>=2&&pinchRef.current){if(pinchFrameRef.current===null)pinchFrameRef.current=window.requestAnimationFrame(()=>{pinchFrameRef.current=null;const pinch=pinchRef.current,wrap=wrapRef.current,shell=shellRef.current,stage=stageRef.current;if(!pinch||!wrap||!shell||!stage||!plan||pointsRef.current.size<2)return;const[a,b]=[...pointsRef.current.values()],mx=(a.x+b.x)/2,my=(a.y+b.y)/2,value=Math.max(.35,Math.min(2.4,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/pinch.distance));zoomRef.current=value;shell.style.transform=`scale(${value})`;stage.style.width=`${(axis*2+plan.width*cell)*value}px`;stage.style.height=`${(axis*2+plan.height*cell)*value}px`;const rect=shell.getBoundingClientRect();wrap.scrollLeft+=rect.left+pinch.anchorX*value-mx;wrap.scrollTop+=rect.top+pinch.anchorY*value-my})}else{const drag=dragRef.current;if(drag&&drag.id===e.pointerId){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.ox,e.clientY-drag.oy)>8)drag.moved=true;wrapRef.current.scrollLeft-=dx;wrapRef.current.scrollTop-=dy;drag.x=e.clientX;drag.y=e.clientY}}e.preventDefault()}
  const pointerUp=(e:React.PointerEvent<HTMLElement>)=>{const drag=dragRef.current,wasSingle=pointsRef.current.size===1;pointsRef.current.delete(e.pointerId);if(wasSingle&&drag&&drag.id===e.pointerId&&!drag.moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('[data-cell]'),index=Number(target?.dataset.cell);if(Number.isFinite(index)&&plan?.cells[index]){suppressClickRef.current=performance.now()+700;choose(plan.cells[index])}}if(pointsRef.current.size===1){const[id,p]=[...pointsRef.current.entries()][0];dragRef.current={id,x:p.x,y:p.y,ox:p.x,oy:p.y,moved:true}}else dragRef.current=null;if(pointsRef.current.size<2){cancelPinchFrame();pinchRef.current=null}}
  const pointerCancel=(e:React.PointerEvent<HTMLElement>)=>{pointsRef.current.delete(e.pointerId);if(dragRef.current?.id===e.pointerId)dragRef.current=null;if(pointsRef.current.size<2){cancelPinchFrame();pinchRef.current=null}}
  const renderBoard=(value:BlueprintPlan)=><section ref={wrapRef} className="blueprint-board-wrap" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerCancel} onLostPointerCapture={pointerCancel}><div ref={stageRef} className="blueprint-stage"><div ref={shellRef} className="blueprint-grid-shell" style={{width:axis*2+value.width*cell,height:axis*2+value.height*cell}}><div className="column-labels top" style={{left:axis,gridTemplateColumns:`repeat(${value.width},${cell}px)`}}>{Array.from({length:value.width},(_,i)=><b key={i}>{i+1}</b>)}</div><div className="column-labels bottom" style={{left:axis,top:axis+value.height*cell,gridTemplateColumns:`repeat(${value.width},${cell}px)`}}>{Array.from({length:value.width},(_,i)=><b key={i}>{i+1}</b>)}</div><div className="row-labels left" style={{top:axis,gridTemplateRows:`repeat(${value.height},${cell}px)`}}>{Array.from({length:value.height},(_,i)=><b key={i}>{i+1}</b>)}</div><div className="row-labels right" style={{left:axis+value.width*cell,top:axis,gridTemplateRows:`repeat(${value.height},${cell}px)`}}>{Array.from({length:value.height},(_,i)=><b key={i}>{i+1}</b>)}</div><div className="blueprint-board" style={{left:axis,top:axis,width:value.width*cell,height:value.height*cell,gridTemplateColumns:`repeat(${value.width},${cell}px)`,gridTemplateRows:`repeat(${value.height},${cell}px)`,backgroundSize:`${cell}px ${cell}px`}}>{value.cells.map((item,index)=>{const key=`${item.x}-${item.y}`,selection=item.groupId??key;return <div key={`${key}-${index}`} data-cell={index} onClick={()=>{if(performance.now()>=suppressClickRef.current)choose(item)}} className={`bp-cell ${item.type} ${item.texture??''} pitch-${item.label??0} ${canSelectPlaybackStart(item)&&selected===selection?'start-selected':''} ${item.step===playingStep?'active-note':''} ${item.type==='note'&&(particles.includes(item.step??-1)||previewCell===key)?'particle-note':''}`} style={{gridColumn:item.x+1,gridRow:item.y+1,width:cell,height:cell}}>{item.type==='repeater'?<div className={`repeater-mark ${item.direction}`}><b>{item.delay}</b></div>:item.type==='dust'?<>{item.connections?.map(d=><i key={d} className={`dust-arm ${d}`}/>) }<i className="dust-dot"/></>:item.type==='note'?<b>{item.label}</b>:item.type==='source'?<b>S</b>:null}</div>})}</div></div></div></section>
  return <main className={`blueprint-page theme-${theme}`}><header className="blueprint-header"><div className="blueprint-brand"><img className="brand-icon" src="/assets/branding/oto-blogic-icon.png" alt="OTO BLOGIC"/><div><img className="brand-logo" src="/assets/branding/oto-blogic-logo.png" alt="OTO BLOGIC"/><h1>{project.title}</h1></div></div><strong>{ja?'回路設計図':'BLUEPRINT'}</strong><button className="editor-back" onClick={onBack}><img src="/assets/icons/keyboard.svg" alt=""/></button></header>
    <nav className="blueprint-tabs">{(['easy','packed','fishbone'] as const).map((value,index)=><button key={value} className={kind===value?'active':''} onClick={()=>{setKind(value);setLayerIndex(0);setSelected(null)}}>0{index+1}<small>{value==='easy'?(ja?'かんたん':'EASY'):value==='packed'?(ja?'詰め詰め':'COMPACT'):(ja?'フィッシュボーン':'FISHBONE')}</small></button>)}</nav>
    {kind==='fishbone'?<section className="blueprint-pending"><b>03</b><h2>{ja?'フィッシュボーン回路':'FISHBONE CIRCUIT'}</h2><span>COMING SOON</span></section>:<><section className="blueprint-controls"><div className="blueprint-transport"><button className="play" onClick={play}><img className="transport-icon" src={playingStep>=0?'/assets/icons/stop.svg':'/assets/icons/play.svg'} alt=""/></button><button className="cue" onClick={cue}><img className="transport-icon" src="/assets/icons/cue.svg" alt=""/></button></div><button className={`control-action ${showOptions?'active':''}`} onClick={()=>{setShowOptions(!showOptions);setShowExport(false)}}><img className="settings-icon" src="/assets/icons/settings.svg" alt=""/><small>{ja?'設定':'SETTINGS'}</small></button><button className={`control-action export-toggle ${showExport?'active':''}`} onClick={()=>{setShowExport(!showExport);setShowOptions(false)}}><span>⇩</span><small>{ja?'出力':'EXPORT'}</small></button><button className={`control-action legend-toggle ${showLegend?'active':''}`} onClick={()=>setShowLegend(!showLegend)}><span>ⓘ</span><small>{ja?'図の説明':'LEGEND'}</small></button></section>
      {showOptions&&<section className="blueprint-options"><label><span>{kind==='packed'?(ja?'作成範囲':'BUILD AREA'):(ja?'折り返しまで':'RUN LENGTH')}</span><span className="number-stepper blueprint-stepper"><strong>{kind==='packed'?compactSize:runLength}</strong><em>{kind==='packed'?`×${compactSize}`:(ja?'マス':'BLOCKS')}</em><span><button onPointerDown={e=>startHold(1,e)} onPointerUp={stopHold}>▲</button><button onPointerDown={e=>startHold(-1,e)} onPointerUp={stopHold}>▼</button></span></span></label>{kind==='easy'&&<label><span>{ja?'折り返す方向':'FOLD TOWARD'}</span><button className="single-toggle" onClick={()=>{const next=fold==='right'?'left':'right';setFold(next);save({fold:next})}}>{fold==='right'?'→':'←'}</button></label>}<label><span>{ja?'前後の無音':'SILENT EDGES'}</span><button className={`single-toggle ${includeSilentEdges?'active':''}`} onClick={()=>{setIncludeSilentEdges(!includeSilentEdges);save({includeSilentEdges:!includeSilentEdges})}}>{includeSilentEdges?(ja?'含める':'INCLUDE'):(ja?'省く':'TRIM')}</button></label><label><span>{ja?'背景色':'BACKGROUND'}</span><button className="single-toggle" onClick={()=>{const next=theme==='dark'?'light':'dark';setTheme(next);save({theme:next})}}>{theme==='dark'?'DARK':'WHITE'}</button></label></section>}
      {showExport&&plan&&<section className="blueprint-export-panel"><button onClick={()=>kind==='packed'&&compact?exportBlueprintLayers(compact.layers,'png',project.title,theme,usedBlocks,ja):exportBlueprint(plan,'png',project.title,theme,usedBlocks,ja)}><b>PNG</b><span>{kind==='packed'&&compact&&compact.layers.length>1?(ja?'レイヤーをZIP保存':'LAYERS AS ZIP'):(ja?'画像として保存':'SAVE IMAGE')}</span></button><button onClick={()=>kind==='packed'&&compact?exportBlueprintLayers(compact.layers,'pdf',project.title,theme,usedBlocks,ja):exportBlueprint(plan,'pdf',project.title,theme,usedBlocks,ja)}><b>PDF</b><span>{kind==='packed'&&compact&&compact.layers.length>1?(ja?'レイヤーごとに保存':'ONE PAGE PER LAYER'):(ja?'印刷用に保存':'SAVE FOR PRINT')}</span></button></section>}
      {showLegend&&<section className="blueprint-legend">{usedBlocks.map(block=><span key={block.texture}><i className="legend-note" style={{'--legend-texture':`url('/assets/block-textures/${textureFiles[block.texture]}')`} as React.CSSProperties}>{block.label}</i>{block.name}</span>)}<span><i className="legend-repeater"><span className="repeater-mark down"><b>1</b></span></i>{ja?'リピーターの向きと遅延数':'REPEATER'}</span><span><i className="legend-rest placeholder"/>{ja?'仮ブロック：任意の不透過ブロック':'ANY SOLID BLOCK'}</span><span><i className="legend-dust"><u/></i>{ja?'レッドストーンダスト':'DUST'}</span><span><i className="legend-source">S</i>{ja?'スタート':'START'}</span></section>}
      {!eligible?<section className="blueprint-warning"><b>!</b><div><strong>{ja?'この回路では生成できません':'NOT AVAILABLE'}</strong><p>{ja?`最大同時発音数が${poly}音です。${kind==='easy'?3:6}音以内にしてください。`:`Polyphony ${poly}; limit ${kind==='easy'?3:6}.`}</p></div></section>:plan&&<>{kind==='packed'&&compact&&compact.layers.length>1&&<nav className="blueprint-layers">{compact.layers.map((_,i)=><button key={i} className={i===layerIndex?'active':''} onClick={()=>setLayerIndex(i)}>{ja?`レイヤー ${i+1}`:`LAYER ${i+1}`}</button>)}</nav>}{renderBoard(plan)}</>}</>}
  </main>
}
