import './editorGuide.css'
import {traditionalizeRecord} from './localization'

type Props={language:string;setLanguage:(language:string)=>void;onBack:()=>void;onHome:()=>void}
type GuideItem={icon:string;title:string;body:string;image?:string;invert?:boolean;danger?:boolean}

const jaSections:{title:string;intro:string;items:GuideItem[]}[]=[
  {title:'再生と曲の設定',intro:'曲全体の速さと長さを決め、再生しながら音を確かめます。',items:[
    {icon:'',image:'/assets/icons/play.svg',invert:true,title:'再生／停止',body:'再生ヘッドの位置から演奏します。再生中に押すと音も含めてすぐ停止します。'},
    {icon:'',image:'/assets/icons/cue.svg',invert:true,title:'頭出し',body:'再生ヘッドを曲の先頭へ戻します。'},
    {icon:'150',title:'BPM',body:'曲のテンポを設定します。Minecraftのティックレート換算値も表示します。'},
    {icon:'▥',title:'小節数',body:'曲の長さを小節単位で変更します。数字の直接入力と▲▼の長押しに対応します。'},
    {icon:'≋',title:'最大同時発音数',body:'同じタイミングに鳴るノートの最大数です。生成できる音符ブロック回路を判断する目安になります。'},
  ]},
  {title:'トラックと音色',intro:'20トラックを使い分け、音色・音量・PANを組み合わせられます。',items:[
    {icon:'01',title:'選択中のトラック',body:'トラック一覧を開きます。各トラックのゴースト、ミュート、ソロ、音量も変更できます。'},
    {icon:'',image:'/assets/icons/settings.svg',title:'トラック設定',body:'トラック名、音色、音量、ミュート、ソロ、PANをまとめて設定します。'},
    {icon:'◉',title:'ゴースト',body:'他トラックのノートを色付きの枠線で表示します。ゴーストは参照用で編集されません。'},
    {icon:'M',title:'ミュート（M）',body:'そのトラックだけを消音します。ノートは削除されず、解除すると再び鳴ります。'},
    {icon:'S',title:'ソロ（S）',body:'ソロを有効にしたトラックだけを再生します。複数トラックを同時にソロにできます。'},
    {icon:'VOL',title:'音量',body:'打ち込み画面で試聴するトラック音量を調整します。設計図画面の再生には反映されません。'},
    {icon:'PAN',title:'PAN',body:'打ち込み画面で試聴する音の左右位置を調整します。設計図画面の再生には反映されません。'},
  ]},
  {title:'ノートの入力と編集',intro:'ピアノロールをタップして音を置き、ドラッグや範囲操作で整えます。',items:[
    {icon:'✎',title:'入力',body:'空のマスを短くタップするとノートを設置します。ノートをドラッグすると移動し、短くタップすると削除します。'},
    {icon:'▧',title:'範囲選択',body:'ドラッグした長方形の範囲を選択します。範囲内のノートを掴むと、まとめて移動できます。'},
    {icon:'⧉',title:'コピー',body:'選択範囲内のノートを一時保存します。コピーできるとアイコンがチェック表示に変わります。'},
    {icon:'⎘',title:'貼付',body:'コピーしたノートを再生ヘッドの位置へ貼り付け、再生ヘッドを貼付範囲の末尾へ進めます。'},
    {icon:'⌫',danger:true,title:'削除',body:'範囲選択したノートをまとめて削除します。'},
    {icon:'− ＋',title:'小節幅の縮小／拡大',body:'1ステップの縦幅を調整し、曲全体の確認や細かな編集をしやすくします。'},
  ]},
  {title:'ピアノロールの操作',intro:'時間は縦方向へ進み、横方向に低音から高音まで25音を配置しています。',items:[
    {icon:'ド',title:'鍵盤と音名',body:'上部の鍵盤で音を試聴できます。右端のボタンでドレミと音符ブロックのクリック数を切り替えます。'},
    {icon:'│',title:'再生ヘッド',body:'小節番号列の横線をタップすると再生位置を移動します。ダブルタップするとそこから再生します。'},
    {icon:'↕',title:'スクロール',body:'ノートのない打ち込み領域をスワイプして移動します。範囲選択中は小節番号列でもスクロールできます。'},
  ]},
  {title:'履歴・遅延・ファイル',intro:'下部メニューから編集履歴、Minecraft向けの遅延単位、保存や設計図生成を操作します。',items:[
    {icon:'↶ ↷',title:'UNDO／REDO',body:'直前の編集を元に戻す、またはやり直します。'},
    {icon:'',image:'/assets/icons/delay-mode.svg',invert:true,title:'遅延モード',body:'グリッド1目盛りを1・2・4遅延から選びます。ゆっくりした曲では回路を短くできます。'},
    {icon:'•••',title:'メニュー',body:'設計図生成、.OBGファイルの保存・読み込み、ホーム、全削除などを開きます。'},
  ]},
]

const enSections:{title:string;intro:string;items:GuideItem[]}[]=jaSections.map((section,index)=>({title:['PLAYBACK & SONG','TRACKS & INSTRUMENTS','NOTE ENTRY & EDITING','PIANO ROLL','HISTORY, DELAY & FILES'][index],intro:['Set the song speed and length, then audition your arrangement.','Arrange up to 20 tracks with individual instruments, volume, and PAN.','Place notes, then refine them with drag and selection tools.','Time moves vertically while 25 pitches run from low to high.','Use the bottom dock for history, delay units, files, and blueprints.'][index],items:section.items.map((item,itemIndex)=>({...item,title:[['PLAY / STOP','RETURN TO START','BPM','BARS','MAX POLYPHONY'],['ACTIVE TRACK','TRACK SETTINGS','GHOST NOTES','MUTE (M)','SOLO (S)','VOLUME','PAN'],['DRAW','SELECT','COPY','PASTE','DELETE','GRID ZOOM'],['KEYS & PITCHES','PLAYHEAD','SCROLL'],['UNDO / REDO','DELAY MODE','MENU']][index][itemIndex],body:[['Starts at the playhead. Press again to stop immediately.','Moves the playhead to the beginning.','Sets BPM and shows the Minecraft tick-rate equivalent.','Changes song length by typing or holding the arrows.','Shows the highest number of simultaneous notes.'],['Opens the track list and its ghost, mute, solo, and volume controls.','Edits track name, instrument, volume, mute, solo, and PAN.','Shows other tracks as non-editable colored outlines.','Silences only this track without deleting its notes.','Plays only soloed tracks. More than one track can be soloed.','Sets editor-preview volume. It does not affect blueprint playback.','Sets editor-preview stereo position. It does not affect blueprint playback.'],['Tap to add a note. Drag a note to move it, or tap it to delete it.','Drag a rectangle to select notes, then drag a selected note to move the group.','Copies the selected notes. A check mark confirms the action.','Pastes at the playhead and moves it to the phrase end.','Deletes every note in the selection.','Changes row height for overview or precision.'],['Tap keys to audition pitches and switch between names and click counts.','Tap the bar-number column to seek, or double-tap to play.','Swipe empty roll space to scroll.'],['Undo or redo the latest editing operation.','Sets each grid step to 1, 2, or 4 repeater delay units.','Opens blueprints, .OBG files, home, and clear-all actions.']][index][itemIndex]}))}))
enSections[3].items[0].icon='ABC'

type GuideLocale={hero:string;lead:string;back:string;returnLabel:string;sectionTitles:string[];sectionIntros:string[];itemTitles:string[][];itemBodies:string[][]}
const guideLocales:Record<string,GuideLocale>={
  es:{hero:'GUÍA DEL EDITOR',lead:'Guía para crear música de bloques de notas de Minecraft con el piano roll de OTO BLOGIC.',back:'EDITOR',returnLabel:'VOLVER AL EDITOR',sectionTitles:['REPRODUCCIÓN Y CANCIÓN','PISTAS E INSTRUMENTOS','EDICIÓN DE NOTAS','PIANO ROLL','HISTORIAL, RETARDO Y ARCHIVOS'],sectionIntros:['Ajusta velocidad y duración, y escucha el resultado.','Combina hasta 20 pistas, instrumentos, volumen y PAN.','Coloca notas y edítalas con arrastre y selección.','El tiempo avanza en vertical y hay 25 alturas.','Controla historial, retardo, archivos y planos.'],itemTitles:[['REPRODUCIR / PARAR','IR AL INICIO','BPM','COMPASES','POLIFONÍA MÁX.'],['PISTA ACTIVA','AJUSTES DE PISTA','NOTAS FANTASMA','SILENCIAR (M)','SOLO (S)','VOLUMEN','PAN'],['DIBUJAR','SELECCIONAR','COPIAR','PEGAR','BORRAR','ALTURA DE CELDA'],['TECLAS Y ALTURAS','CABEZAL','DESPLAZAR'],['DESHACER / REHACER','MODO DE RETARDO','MENÚ']],itemBodies:[['Reproduce desde el cabezal. Pulsa otra vez para parar al instante.','Mueve el cabezal al inicio.','Ajusta BPM y muestra su equivalencia en tick rate.','Cambia la duración escribiendo o manteniendo las flechas.','Muestra el mayor número de notas simultáneas.'],['Abre la lista y los controles de fantasma, M, S y volumen.','Edita nombre, instrumento, volumen, M, S y PAN.','Muestra otras pistas como contornos no editables.','Silencia esta pista sin borrar sus notas.','Reproduce solo las pistas con S activo.','Volumen de escucha en el editor; no afecta al plano.','Posición estéreo en el editor; no afecta al plano.'],['Toca para añadir. Arrastra para mover o toca una nota para borrarla.','Arrastra un rectángulo y mueve todas las notas seleccionadas.','Guarda temporalmente las notas seleccionadas.','Pega en el cabezal y lo mueve al final de la frase.','Borra todas las notas seleccionadas.','Ajusta la altura de las filas.'],['Toca las teclas y cambia entre nombres y clics.','Toca la columna de compases para moverlo; doble toque para reproducir.','Desliza una zona vacía para desplazarte.'],['Deshace o rehace la última edición.','Usa 1, 2 o 4 unidades de retardo por celda.','Abre planos, archivos .OBG, inicio y borrar todo.']]},
  fr:{hero:"GUIDE DE L’ÉDITEUR",lead:'Guide du piano roll OTO BLOGIC pour composer avec les blocs musicaux de Minecraft.',back:'ÉDITEUR',returnLabel:"RETOUR À L’ÉDITEUR",sectionTitles:['LECTURE ET MORCEAU','PISTES ET INSTRUMENTS','ÉDITION DES NOTES','PIANO ROLL','HISTORIQUE, DÉLAI ET FICHIERS'],sectionIntros:['Réglez la vitesse et la longueur, puis écoutez.','Combinez 20 pistes, instruments, volume et PAN.','Placez puis modifiez les notes.','Le temps descend verticalement sur 25 hauteurs.','Gérez historique, délai, fichiers et plans.'],itemTitles:[['LIRE / ARRÊTER','REVENIR AU DÉBUT','BPM','MESURES','POLYPHONIE MAX.'],['PISTE ACTIVE','RÉGLAGES DE PISTE','NOTES FANTÔMES','MUET (M)','SOLO (S)','VOLUME','PAN'],['DESSINER','SÉLECTIONNER','COPIER','COLLER','SUPPRIMER','HAUTEUR DE GRILLE'],['TOUCHES ET HAUTEURS','TÊTE DE LECTURE','DÉFILER'],['ANNULER / RÉTABLIR','MODE DE DÉLAI','MENU']],itemBodies:[['Lit depuis la tête de lecture. Appuyez encore pour arrêter immédiatement.','Replace la tête de lecture au début.','Règle le BPM et affiche son équivalent en tick rate.','Modifie la longueur par saisie ou appui prolongé.','Affiche le plus grand nombre de notes simultanées.'],['Ouvre la liste et les contrôles fantôme, M, S et volume.','Modifie nom, instrument, volume, M, S et PAN.','Affiche les autres pistes en contours non modifiables.','Coupe cette piste sans supprimer ses notes.','Ne lit que les pistes dont S est actif.','Volume d’écoute dans l’éditeur uniquement, pas dans le plan.','Position stéréo dans l’éditeur uniquement, pas dans le plan.'],['Touchez pour ajouter, glissez pour déplacer, touchez une note pour supprimer.','Tracez un rectangle puis déplacez le groupe sélectionné.','Mémorise temporairement les notes sélectionnées.','Colle à la tête de lecture puis avance à la fin du motif.','Supprime toutes les notes sélectionnées.','Ajuste la hauteur des lignes.'],['Touchez les touches et alternez noms et nombre de clics.','Touchez la colonne des mesures pour déplacer; double-touchez pour lire.','Glissez une zone vide pour défiler.'],['Annule ou rétablit la dernière modification.','Choisit 1, 2 ou 4 unités de délai par case.','Ouvre plans, fichiers .OBG, accueil et tout effacer.']]},
  de:{hero:'EDITOR-ANLEITUNG',lead:'Anleitung zum Komponieren von Minecraft-Notenblockmusik im OTO BLOGIC Piano-Roll.',back:'EDITOR',returnLabel:'ZUM EDITOR',sectionTitles:['WIEDERGABE & SONG','SPUREN & INSTRUMENTE','NOTEN BEARBEITEN','PIANO-ROLL','VERLAUF, DELAY & DATEIEN'],sectionIntros:['Tempo und Länge einstellen und den Song prüfen.','Bis zu 20 Spuren mit Instrument, Lautstärke und PAN.','Noten setzen, ziehen und auswählen.','Die Zeit läuft vertikal durch 25 Tonhöhen.','Verlauf, Delay, Dateien und Baupläne verwalten.'],itemTitles:[['START / STOPP','ZUM ANFANG','BPM','TAKTE','MAX. POLYPHONIE'],['AKTIVE SPUR','SPUREINSTELLUNGEN','GHOST-NOTEN','STUMM (M)','SOLO (S)','LAUTSTÄRKE','PAN'],['ZEICHNEN','AUSWÄHLEN','KOPIEREN','EINFÜGEN','LÖSCHEN','ZEILENHÖHE'],['TASTEN & TÖNE','ABSPIELKOPF','SCROLLEN'],['RÜCKGÄNGIG / WIEDERHOLEN','DELAY-MODUS','MENÜ']],itemBodies:[['Spielt ab dem Abspielkopf. Nochmals drücken stoppt sofort.','Setzt den Abspielkopf an den Anfang.','Stellt BPM ein und zeigt den Tick-Rate-Wert.','Ändert die Länge per Eingabe oder gehaltenen Pfeilen.','Zeigt die höchste Zahl gleichzeitiger Noten.'],['Öffnet Liste sowie Ghost-, M-, S- und Lautstärkeregler.','Ändert Name, Instrument, Lautstärke, M, S und PAN.','Zeigt andere Spuren als nicht editierbare Konturen.','Schaltet nur diese Spur stumm, ohne Noten zu löschen.','Spielt nur Spuren mit aktivem S; mehrere sind möglich.','Lautstärke nur für den Editor, nicht für Bauplan-Wiedergabe.','Stereoposition nur für den Editor, nicht für Bauplan-Wiedergabe.'],['Tippen setzt eine Note; Ziehen verschiebt; kurzes Tippen löscht.','Rechteck ziehen und die ausgewählte Gruppe verschieben.','Speichert ausgewählte Noten vorübergehend.','Fügt am Abspielkopf ein und springt ans Phrasenende.','Löscht alle ausgewählten Noten.','Passt die Zeilenhöhe an.'],['Tasten antippen und zwischen Namen und Klickzahlen wechseln.','Taktspalte antippen zum Springen; doppeltippen zum Abspielen.','In leerem Bereich wischen zum Scrollen.'],['Macht die letzte Bearbeitung rückgängig oder stellt sie wieder her.','Wählt 1, 2 oder 4 Delay-Einheiten pro Rasterfeld.','Öffnet Baupläne, .OBG-Dateien, Startseite und Alles löschen.']]},
  zh:{hero:'编辑器使用指南',lead:'使用 OTO BLOGIC 钢琴卷帘制作 Minecraft 音符盒音乐的操作指南。',back:'编辑器',returnLabel:'返回编辑器',sectionTitles:['播放与乐曲','音轨与音色','音符编辑','钢琴卷帘','历史、延迟与文件'],sectionIntros:['设置速度和长度并试听。','组合20条音轨、音色、音量与PAN。','放置、拖动和选择音符。','时间纵向前进，共有25个音高。','管理历史、延迟、文件和蓝图。'],itemTitles:[['播放／停止','返回开头','BPM','小节数','最大复音数'],['当前音轨','音轨设置','重影音符','静音（M）','独奏（S）','音量','PAN'],['输入','范围选择','复制','粘贴','删除','网格高度'],['键盘与音高','播放头','滚动'],['撤销／重做','延迟模式','菜单']],itemBodies:[['从播放头开始；再次按下会立即停止。','将播放头移到开头。','设置BPM并显示对应tick rate。','输入数字或长按箭头改变曲长。','显示同一时刻最多的音符数。'],['打开音轨列表及重影、M、S和音量控制。','设置名称、音色、音量、M、S与PAN。','以不可编辑的彩色轮廓显示其他音轨。','仅静音此音轨，不会删除音符。','只播放开启S的音轨，可同时开启多条。','仅调整编辑器试听音量，不影响蓝图播放。','仅调整编辑器试听左右位置，不影响蓝图播放。'],['轻点添加，拖动移动，轻点已有音符可删除。','拖出矩形并整体移动选中的音符。','临时保存选中的音符。','粘贴到播放头并移动到乐句末尾。','删除范围内全部音符。','调整每行高度。'],['轻点键盘试听，并切换音名与点击次数。','轻点小节列移动；双击从该处播放。','在空白区域滑动来滚动。'],['撤销或重做最近一次编辑。','每格选择1、2或4延迟。','打开蓝图、.OBG文件、首页和全部清除。']]},
  ko:{hero:'편집 화면 사용법',lead:'OTO BLOGIC 피아노 롤로 Minecraft 소리 블록 음악을 만드는 방법입니다.',back:'편집',returnLabel:'편집 화면으로',sectionTitles:['재생과 곡 설정','트랙과 악기','노트 편집','피아노 롤','기록·지연·파일'],sectionIntros:['속도와 길이를 정하고 곡을 확인합니다.','20트랙의 악기·음량·PAN을 조합합니다.','노트를 놓고 드래그와 범위로 편집합니다.','시간은 세로로 흐르며 25개 음높이를 사용합니다.','기록, 지연, 파일과 설계도를 관리합니다.'],itemTitles:[['재생／정지','처음으로','BPM','마디 수','최대 동시 발음'],['선택 트랙','트랙 설정','고스트 노트','음소거（M）','솔로（S）','음량','PAN'],['입력','범위 선택','복사','붙여넣기','삭제','그리드 높이'],['건반과 음높이','재생 헤드','스크롤'],['실행 취소／다시 실행','지연 모드','메뉴']],itemBodies:[['재생 헤드부터 재생하며 다시 누르면 즉시 멈춥니다.','재생 헤드를 곡 처음으로 이동합니다.','BPM과 Minecraft tick rate 환산값을 표시합니다.','직접 입력하거나 화살표를 길게 눌러 곡 길이를 바꿉니다.','동시에 울리는 노트의 최대 개수입니다.'],['트랙 목록과 고스트, M, S, 음량 조절을 엽니다.','이름, 악기, 음량, M, S와 PAN을 설정합니다.','다른 트랙을 편집할 수 없는 색 테두리로 표시합니다.','노트를 지우지 않고 이 트랙만 끕니다.','S가 켜진 트랙만 재생하며 여러 개를 선택할 수 있습니다.','편집 화면의 미리 듣기 음량이며 설계도 재생에는 적용되지 않습니다.','편집 화면의 좌우 위치이며 설계도 재생에는 적용되지 않습니다.'],['짧게 눌러 추가하고 드래그로 이동하며 기존 노트를 누르면 삭제합니다.','사각형으로 선택하고 선택된 노트를 함께 이동합니다.','선택한 노트를 임시 저장합니다.','재생 헤드 위치에 붙이고 프레이즈 끝으로 이동합니다.','선택 범위의 노트를 모두 삭제합니다.','행 높이를 조절합니다.'],['건반을 눌러 듣고 음이름과 클릭 수를 바꿉니다.','마디 열을 눌러 이동하고 두 번 누르면 그곳부터 재생합니다.','빈 영역을 밀어 스크롤합니다.'],['마지막 편집을 취소하거나 다시 실행합니다.','한 칸을 1·2·4 지연으로 선택합니다.','설계도, .OBG 파일, 홈과 전체 삭제를 엽니다.']]}
}
guideLocales['zh-tw']=traditionalizeRecord(guideLocales.zh)
guideLocales.id={hero:'PANDUAN EDITOR',lead:'Panduan membuat musik blok not Minecraft dengan piano roll OTO BLOGIC.',back:'EDITOR',returnLabel:'KEMBALI KE EDITOR',sectionTitles:['PEMUTARAN & LAGU','TRACK & INSTRUMEN','EDIT NOT','PIANO ROLL','RIWAYAT, DELAY & FILE'],sectionIntros:['Atur kecepatan dan panjang lalu dengarkan hasilnya.','Gabungkan 20 track, instrumen, volume, dan PAN.','Letakkan, seret, dan pilih not.','Waktu bergerak vertikal pada 25 nada.','Kelola riwayat, delay, file, dan denah.'],itemTitles:[['PUTAR / BERHENTI','KEMBALI KE AWAL','BPM','BIRAMA','POLIFONI MAKS.'],['TRACK AKTIF','PENGATURAN TRACK','GHOST NOTE','MUTE (M)','SOLO (S)','VOLUME','PAN'],['MASUKKAN','PILIH AREA','SALIN','TEMPEL','HAPUS','TINGGI GRID'],['TUTS & NADA','PLAYHEAD','GULIR'],['UNDO / REDO','MODE DELAY','MENU']],itemBodies:[['Memutar dari playhead. Tekan lagi untuk langsung berhenti.','Memindahkan playhead ke awal lagu.','Mengatur BPM dan menampilkan nilai tick rate Minecraft.','Ubah panjang lagu dengan mengetik atau menahan tombol panah.','Menampilkan jumlah not bersamaan terbanyak.'],['Membuka daftar track serta kontrol ghost, M, S, dan volume.','Mengatur nama, instrumen, volume, M, S, dan PAN.','Menampilkan track lain sebagai garis berwarna yang tidak dapat diedit.','Membisukan track ini tanpa menghapus not.','Hanya memutar track dengan S aktif.','Volume pratinjau editor; tidak memengaruhi pemutaran denah.','Posisi stereo editor; tidak memengaruhi pemutaran denah.'],['Ketuk untuk menambah, seret untuk memindah, ketuk not untuk menghapus.','Seret kotak lalu pindahkan semua not yang dipilih.','Menyimpan sementara not yang dipilih.','Menempel di playhead lalu maju ke akhir frasa.','Menghapus semua not dalam pilihan.','Mengatur tinggi baris grid.'],['Ketuk tuts untuk mendengar dan ganti nama not atau jumlah klik.','Ketuk kolom birama untuk berpindah; ketuk dua kali untuk memutar.','Geser area kosong untuk menggulir.'],['Membatalkan atau mengulangi edit terakhir.','Pilih 1, 2, atau 4 unit delay per grid.','Membuka denah, file .OBG, beranda, dan hapus semua.']]}
const localizedSections=(language:string)=>{if(language==='ja')return jaSections;if(language==='en'||!guideLocales[language])return enSections;const copy=guideLocales[language];return enSections.map((section,index)=>({...section,title:copy.sectionTitles[index],intro:copy.sectionIntros[index],items:section.items.map((item,itemIndex)=>({...item,icon:index===3&&itemIndex===0?'ABC':item.icon,title:copy.itemTitles[index][itemIndex],body:copy.itemBodies[index][itemIndex]}))}))}

export default function EditorGuidePage({language,setLanguage,onBack,onHome}:Props){const ja=language==='ja',locale=guideLocales[language],sections=localizedSections(language),hero=ja?'打ち込み画面の使い方':locale?.hero??'HOW TO USE THE EDITOR',lead=ja?'OTO BLOGICのピアノロールでMinecraftの音符ブロック演奏を作曲するための操作ガイドです。各ボタンや入力方法を確認しながら、最初の1音から回路設計図の生成まで進められます。':locale?.lead??'A complete guide to composing Minecraft note-block music in the OTO BLOGIC piano-roll editor.',back=ja?'打ち込みへ':locale?.back??'EDITOR',returnLabel=ja?'打ち込み画面へ戻る':locale?.returnLabel??'BACK TO EDITOR';return <main className="editor-guide-page"><header className="editor-guide-topbar"><button className="editor-guide-brand" onClick={onHome} aria-label={ja?'トップページへ':'Go home'}><img src="/assets/branding/oto-blogic-icon.svg" alt=""/><img src="/assets/branding/oto-blogic-logo.png" alt="OTO BLOGIC"/></button><div><button className="editor-guide-back" onClick={onBack}>← {back}</button><select value={language} onChange={event=>setLanguage(event.target.value)} aria-label="Language"><option value="ja">日本語</option><option value="en">English</option><option value="es">Español</option><option value="fr">Français</option><option value="de">Deutsch</option><option value="zh">简体中文</option><option value="zh-tw">繁體中文</option><option value="ko">한국어</option><option value="id">Bahasa Indonesia</option></select></div></header><section className="editor-guide-hero"><small>EDITOR GUIDE</small><h1>{hero}</h1><p>{lead}</p></section><div className="editor-guide-content">{sections.map((section,index)=><section className="editor-guide-section" key={section.title}><header><b>{String(index+1).padStart(2,'0')}</b><div><h2>{section.title}</h2><p>{section.intro}</p></div></header><div className="editor-guide-grid">{section.items.map(item=><article key={item.title}><span className={`editor-guide-icon ${item.invert?'invert':''} ${item.danger?'danger':''}`}>{item.image?<img src={item.image} alt=""/>:item.icon}</span><div><h3>{item.title}</h3><p>{item.body}</p></div></article>)}</div></section>)}</div><footer className="editor-guide-footer"><button onClick={onBack}>{returnLabel} →</button><span>© 2026 OTO BLOGIC · Powered by SOTA56</span></footer></main>}
