import type {ReactNode} from 'react'
import './legal.css'

type Props={language:string;setLanguage:(language:string)=>void;kind:'terms'|'privacy';onHome:()=>void;onTerms:()=>void;onPrivacy:()=>void}
type Section={title:string;body:ReactNode[]}
type Copy={terms:string;privacy:string;updated:string;home:string;intro:string;sections:Section[]}
const languages=[['ja','日本語'],['en','English'],['es','Español'],['fr','Français'],['de','Deutsch'],['zh','简体中文'],['zh-tw','繁體中文'],['ko','한국어'],['id','Bahasa Indonesia']]
const external=(href:string,label:string)=><a href={href} target="_blank" rel="noreferrer">{label}</a>

const termsJa:Copy={terms:'利用規約',privacy:'プライバシーポリシー',updated:'最終更新：2026年7月22日',home:'ホームへ',intro:'OTO BLOGICを安心して使い、作ったものを気持ちよく共有するためのルールです。',sections:[
 {title:'サービスについて',body:['OTO BLOGICは、Minecraftの音符ブロック演奏の作曲と回路設計を助ける無料のWebツールです。利用者は、本規約に同意したうえで本サービスを利用するものとします。']},
 {title:'設計図を公開するとき',body:[<>OTO BLOGICが生成した設計図、設計図の画像・PDF、または設計図を中心に紹介する動画や記事を公開するときは、見つけやすい場所に「OTO BLOGIC」とクレジットを記載してください。可能であれば {external('https://otoblogic.com','https://otoblogic.com')} へのリンクもお願いします。</>,'この条件は、利用者が作曲した曲や、利用者自身が制作したMinecraft作品の権利をOTO BLOGICへ移すものではありません。']},
 {title:'禁止事項',body:['法令や第三者の権利を侵害する行為、本サービスの運営を妨げる行為、不正アクセス、過度な負荷を与える行為、OTO BLOGICの名称や設計図を使って公式サービスであるかのように誤認させる行為は禁止します。']},
 {title:'保存データと免責',body:['曲データの自動保存は利用中のブラウザ内で行われます。端末やブラウザの設定変更、データ削除、故障などに備え、重要な曲は.OBGファイルでも保存してください。','本サービスは正確性や継続提供を保証するものではありません。利用によって生じた損害について、運営者は法令上認められる範囲で責任を負いません。']},
 {title:'変更・停止',body:['機能、内容、本規約は必要に応じて変更されることがあります。大きな変更がある場合は、サイト上で分かるようにお知らせします。']},
 {title:'Minecraftとの関係',body:['OTO BLOGICはMinecraftファンが制作・運営する非公式のファンサイト／ツールです。Mojang StudiosまたはMicrosoftによって承認、提携、後援されたものではありません。Minecraftの名称、ゲーム画像などに関する権利は、それぞれの権利者に帰属します。',external('https://www.minecraft.net/usage-guidelines','Minecraft Usage Guidelines（公式）')]},
 {title:'お問い合わせ',body:[<>本サービスに関する連絡は {external('https://x.com/OTOBLOGIC','OTO BLOGIC公式X')} へお願いします。</>]},
]}

const privacyJa:Copy={terms:'利用規約',privacy:'プライバシーポリシー',updated:'最終更新：2026年7月22日',home:'ホームへ',intro:'OTO BLOGICで扱う情報と、利用者が選べるプライバシー設定を説明します。',sections:[
 {title:'ブラウザ内に保存する情報',body:['曲名、音符、トラック設定、設計図設定、言語設定などは、利用中の端末のブラウザ内（Local Storage）に保存されます。これらの曲データは、通常の利用ではOTO BLOGICのサーバーへ送信されません。']},
 {title:'Google Analytics',body:['サイトの改善のため、同意した利用者に限りGoogle Analytics 4を使用します。ページの閲覧、利用端末・ブラウザ、セッション、国や地域のおおよその情報などがGoogleへ送信されます。氏名、メールアドレス、作曲内容などを意図的に送信することはありません。','同意するまではGoogle Analyticsのタグを読み込まず、Googleへ解析データを送信しません。拒否してもOTO BLOGICの作曲・設計図機能は利用できます。',external('https://policies.google.com/technologies/partner-sites?hl=ja','Googleによる情報の使用について')]},
 {title:'同意の変更',body:['選択内容はブラウザ内に保存されます。トップページ下部の「Cookie設定」から、いつでも解析への同意を変更できます。ブラウザの保存データを削除した場合は、選択をもう一度確認します。']},
 {title:'外部サービス',body:['YouTube動画、Buy Me a Coffee、X、GitHubなどの外部サービスを表示または開く場合、各サービスがアクセス情報などを扱うことがあります。各サービスのプライバシーポリシーもご確認ください。']},
 {title:'お問い合わせ',body:[<>プライバシーに関する連絡は {external('https://x.com/OTOBLOGIC','OTO BLOGIC公式X')} へお願いします。</>]},
]}

const termsEn:Copy={terms:'TERMS OF USE',privacy:'PRIVACY POLICY',updated:'Last updated: July 22, 2026',home:'HOME',intro:'Simple rules for using OTO BLOGIC and sharing what you create.',sections:[
 {title:'About the service',body:['OTO BLOGIC is a free web tool for composing Minecraft note-block music and generating circuit blueprints. By using it, you agree to these terms.']},
 {title:'Credit when sharing blueprints',body:[<>When publishing a blueprint generated by OTO BLOGIC, an exported image or PDF, or a video or article mainly featuring that blueprint, include the credit “OTO BLOGIC” where it can be easily found. A link to {external('https://otoblogic.com','https://otoblogic.com')} is appreciated.</>,'This requirement does not transfer ownership of your music or your own Minecraft builds to OTO BLOGIC.']},
 {title:'Prohibited use',body:['Do not break laws or third-party rights, disrupt the service, attempt unauthorized access, place excessive load on it, or present OTO BLOGIC or its blueprints as an official Minecraft service.']},
 {title:'Saved data and disclaimer',body:['Autosaved song data stays in your browser. Save important work as an .OBG file as well. The service is provided without guarantees of accuracy or continuous availability.']},
 {title:'Changes',body:['Features, content, and these terms may change when necessary. Material changes will be announced on the site.']},
 {title:'Minecraft affiliation',body:['OTO BLOGIC is an unofficial fan-made website and tool. It is not approved by, associated with, or endorsed by Mojang Studios or Microsoft. Rights in the Minecraft name and game assets belong to their respective owners.',external('https://www.minecraft.net/usage-guidelines','Official Minecraft Usage Guidelines')]},
 {title:'Contact',body:[<>Contact us through {external('https://x.com/OTOBLOGIC','OTO BLOGIC on X')}.</>]},
]}

const privacyEn:Copy={terms:'TERMS OF USE',privacy:'PRIVACY POLICY',updated:'Last updated: July 22, 2026',home:'HOME',intro:'What OTO BLOGIC stores and the privacy choices available to you.',sections:[
 {title:'Data stored in your browser',body:['Song titles, notes, track settings, blueprint settings, and language preferences are stored in your browser using Local Storage. Song data is not normally sent to OTO BLOGIC servers.']},
 {title:'Google Analytics',body:['With your consent, we use Google Analytics 4 to improve the site. It may collect page views, device and browser details, sessions, and approximate location. We do not intentionally send your name, email address, or song content.','The Analytics tag is not loaded and no analytics data is sent to Google until you consent. Refusing does not limit the composer or blueprint features.',external('https://policies.google.com/technologies/partner-sites','How Google uses information from sites or apps that use its services')]},
 {title:'Changing your choice',body:['Your choice is stored in your browser. Use “Cookie settings” in the home-page footer to change it at any time.']},
 {title:'External services',body:['Embedded or linked services such as YouTube, Buy Me a Coffee, X, and GitHub may process access information under their own privacy policies.']},
 {title:'Contact',body:[<>Contact us through {external('https://x.com/OTOBLOGIC','OTO BLOGIC on X')}.</>]},
]}

const labels:Record<string,{terms:string;privacy:string;home:string;updated:string}>={es:{terms:'TÉRMINOS DE USO',privacy:'POLÍTICA DE PRIVACIDAD',home:'INICIO',updated:'Actualizado: 22 de julio de 2026'},fr:{terms:"CONDITIONS D’UTILISATION",privacy:'POLITIQUE DE CONFIDENTIALITÉ',home:'ACCUEIL',updated:'Mise à jour : 22 juillet 2026'},de:{terms:'NUTZUNGSBEDINGUNGEN',privacy:'DATENSCHUTZ',home:'STARTSEITE',updated:'Stand: 22. Juli 2026'},zh:{terms:'使用条款',privacy:'隐私政策',home:'首页',updated:'更新日期：2026年7月22日'},'zh-tw':{terms:'使用條款',privacy:'隱私權政策',home:'首頁',updated:'更新日期：2026年7月22日'},ko:{terms:'이용약관',privacy:'개인정보 처리방침',home:'홈',updated:'최종 업데이트: 2026년 7월 22일'},id:{terms:'KETENTUAN PENGGUNAAN',privacy:'KEBIJAKAN PRIVASI',home:'BERANDA',updated:'Diperbarui: 22 Juli 2026'}}
const localized=(base:Copy,language:string):Copy=>labels[language]?{...base,...labels[language]}:base

export default function LegalPage({language,setLanguage,kind,onHome,onTerms,onPrivacy}:Props){const base=kind==='terms'?(language==='ja'?termsJa:termsEn):(language==='ja'?privacyJa:privacyEn),copy=localized(base,language);return <main className="legal-page"><header className="legal-topbar"><button className="legal-brand" onClick={onHome}><img src="/assets/branding/oto-blogic-icon-04.png" alt=""/><img src="/assets/branding/oto-blogic-logo.png" alt="OTO BLOGIC"/></button><div><button className="legal-home" onClick={onHome}>← {copy.home}</button><select value={language} onChange={event=>setLanguage(event.target.value)} aria-label="Language">{languages.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div></header><section className="legal-hero"><small>OTO BLOGIC / LEGAL</small><h1>{kind==='terms'?copy.terms:copy.privacy}</h1><p>{copy.intro}</p><time>{copy.updated}</time></section><div className="legal-content">{copy.sections.map((section,index)=><section key={section.title}><b>{String(index+1).padStart(2,'0')}</b><div><h2>{section.title}</h2>{section.body.map((part,i)=><p key={i}>{part}</p>)}</div></section>)}</div><aside className="legal-unofficial">NOT AN OFFICIAL MINECRAFT PRODUCT. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT.</aside><footer className="legal-footer"><button onClick={kind==='terms'?onPrivacy:onTerms}>{kind==='terms'?copy.privacy:copy.terms} →</button><span>© 2026 OTO BLOGIC · Powered by SOTA56</span></footer></main>}
