import {useState} from 'react'
import {BuyMeCoffeeWidget} from './BuyMeCoffee'
import './resource-pack.css'

type Props={language:string;setLanguage:(language:string)=>void;onHome:()=>void}

const languageOptions=[
  ['ja','日本語'],['en','English'],['es','Español'],['fr','Français'],['de','Deutsch'],
  ['zh','简体中文'],['zh-tw','繁體中文'],['ko','한국어'],['id','Bahasa Indonesia'],
]

const packs:{version:string;file:string;size:string;latest?:boolean}[]=[
  {version:'26.1–26.2',file:'OTO_BLOGIC_VISUALS_26.1-26.2.zip',size:'420 KB',latest:true},
  {version:'1.21.9–26.0',file:'OTO_BLOGIC_VISUALS_1.21.9-26.0.zip',size:'356 KB'},
  {version:'1.20.2–1.21.8',file:'OTO_BLOGIC_VISUALS_1.20.2-1.21.8.zip',size:'356 KB'},
  {version:'1.20–1.20.1',file:'OTO_BLOGIC_VISUALS_1.20-1.20.1.zip',size:'356 KB'},
  {version:'1.19.4',file:'OTO_BLOGIC_VISUALS_1.19.4.zip',size:'356 KB'},
  {version:'1.19.3',file:'OTO_BLOGIC_VISUALS_1.19.3.zip',size:'356 KB'},
  {version:'1.19–1.19.2',file:'OTO_BLOGIC_VISUALS_1.19-1.19.2.zip',size:'356 KB'},
  {version:'1.18–1.18.2',file:'OTO_BLOGIC_VISUALS_1.18-1.18.2.zip',size:'356 KB'},
  {version:'1.17–1.17.1',file:'OTO_BLOGIC_VISUALS_1.17-1.17.1.zip',size:'356 KB'},
  {version:'1.16.2–1.16.5',file:'OTO_BLOGIC_VISUALS_1.16.2-1.16.5.zip',size:'356 KB'},
  {version:'1.16–1.16.1',file:'OTO_BLOGIC_VISUALS_1.16-1.16.1.zip',size:'356 KB'},
  {version:'1.15–1.15.2',file:'OTO_BLOGIC_VISUALS_1.15-1.15.2.zip',size:'356 KB'},
  {version:'1.13–1.14.4',file:'OTO_BLOGIC_VISUALS_1.13-1.14.4.zip',size:'356 KB'},
  {version:'1.12–1.12.2',file:'OTO_BLOGIC_VISUALS_1.12-1.12.2.zip',size:'356 KB'},
]

const bedrockPacks:{version:string;file:string;size:string;latest?:boolean}[]=[
  {version:'26.30+',file:'OTO_BLOGIC_VISUALS_BEDROCK_26.30-plus_v0.2.0.mcpack',size:'12 KB',latest:true},
  {version:'26.0–26.20',file:'OTO_BLOGIC_VISUALS_BEDROCK_26.0-26.20_v0.2.0.mcpack',size:'12 KB'},
]

const copy:Record<string,{title:string;lead:string;edition:string;choose:string;latest:string;download:string;direct:string;what:string;whatText:string;features:string[];install:string;steps:string[];notes:string;noteItems:string[];home:string;version:string}>= {
  ja:{title:'OTO BLOGIC VISUALS',lead:'Minecraftの音符ブロックとリピーターを、もっと読み取りやすくするJAVAバージョン用のリソースパックです。',edition:'MINECRAFT JAVA EDITION',choose:'使っているバージョン',latest:'最新',download:'ZIPをダウンロード',direct:'GitHubからすぐにダウンロードします。GitHubの画面は開きません。',what:'何が見やすくなる？',whatText:'音符ブロックの音程・音の種類と、リピーターの向き・遅延を見た目で確認しやすくします。',features:['音符ブロックの音程','下のブロックで決まる音の種類','リピーターの向きと遅延'],install:'入れ方',steps:['自分のMinecraftに合うZIPを選んでダウンロードします。','ZIPを解凍せず、Minecraftの resourcepacks フォルダーに入れます。','Minecraftの「設定 → リソースパック」から OTO BLOGIC VISUALS を有効にします。'],notes:'対応について',noteItems:['Java版専用です。Bedrock版では使用できません。','1.12ではMinecraftの仕組み上、音程とリピーターのみを表示します。','ゾンビなどの頭部で鳴る音は対象外です。'],home:'ホームへ',version:'Minecraft Java'},
  en:{title:'OTO BLOGIC VISUALS',lead:'A resource pack that makes Minecraft note blocks and repeaters easier to read at a glance.',edition:'MINECRAFT JAVA EDITION',choose:'Choose your version',latest:'LATEST',download:'DOWNLOAD ZIP',direct:'Downloads directly from GitHub without opening a GitHub page.',what:'WHAT DOES IT SHOW?',whatText:'See note-block pitch and instrument, plus repeater direction and delay, directly on the blocks.',features:['Note-block pitch','Instrument set by the block below','Repeater direction and delay'],install:'HOW TO INSTALL',steps:['Choose the ZIP that matches your Minecraft version.','Do not unzip it. Put the ZIP in the Minecraft resourcepacks folder.','Enable OTO BLOGIC VISUALS in Options → Resource Packs.'],notes:'COMPATIBILITY',noteItems:['For Java Edition only. It does not work in Bedrock Edition.','Minecraft 1.12 can show pitch and repeaters, but not the instrument under each note block.','Sounds produced by mob heads are not included.'],home:'HOME',version:'Minecraft Java'},
  es:{title:'OTO BLOGIC VISUALS',lead:'Un paquete de recursos que facilita la lectura de bloques musicales y repetidores.',edition:'MINECRAFT JAVA EDITION',choose:'Elige tu versión',latest:'MÁS RECIENTE',download:'DESCARGAR ZIP',direct:'Descarga directa desde GitHub, sin abrir su página.',what:'¿QUÉ MUESTRA?',whatText:'Muestra la altura y el instrumento del bloque musical, además de la dirección y el retardo del repetidor.',features:['Altura del bloque musical','Instrumento según el bloque inferior','Dirección y retardo del repetidor'],install:'INSTALACIÓN',steps:['Elige el ZIP para tu versión de Minecraft.','No lo descomprimas. Colócalo en la carpeta resourcepacks.','Activa OTO BLOGIC VISUALS en Opciones → Paquetes de recursos.'],notes:'COMPATIBILIDAD',noteItems:['Solo para Java Edition.','En 1.12 se muestran la altura y los repetidores, pero no el instrumento.','No incluye sonidos producidos por cabezas de criaturas.'],home:'INICIO',version:'Minecraft Java'},
  fr:{title:'OTO BLOGIC VISUALS',lead:'Un pack de ressources qui rend les blocs musicaux et les répéteurs plus faciles à lire.',edition:'MINECRAFT JAVA EDITION',choose:'Choisissez votre version',latest:'RÉCENT',download:'TÉLÉCHARGER LE ZIP',direct:'Téléchargement direct depuis GitHub, sans ouvrir sa page.',what:'QUE MONTRE-T-IL ?',whatText:'Affiche la hauteur et l’instrument du bloc musical, ainsi que la direction et le délai du répéteur.',features:['Hauteur du bloc musical','Instrument selon le bloc placé dessous','Direction et délai du répéteur'],install:'INSTALLATION',steps:['Choisissez le ZIP adapté à votre version.','Ne le décompressez pas. Placez-le dans le dossier resourcepacks.','Activez OTO BLOGIC VISUALS dans Options → Packs de ressources.'],notes:'COMPATIBILITÉ',noteItems:['Uniquement pour Java Edition.','En 1.12, la hauteur et les répéteurs sont visibles, mais pas l’instrument.','Les sons produits par les têtes de créatures ne sont pas inclus.'],home:'ACCUEIL',version:'Minecraft Java'},
  de:{title:'OTO BLOGIC VISUALS',lead:'Ein Ressourcenpaket, das Notenblöcke und Repeater leichter lesbar macht.',edition:'MINECRAFT JAVA EDITION',choose:'Version auswählen',latest:'NEUESTE',download:'ZIP HERUNTERLADEN',direct:'Direkter Download von GitHub, ohne eine GitHub-Seite zu öffnen.',what:'WAS WIRD ANGEZEIGT?',whatText:'Tonhöhe und Instrument des Notenblocks sowie Richtung und Verzögerung des Repeaters werden sichtbar.',features:['Tonhöhe des Notenblocks','Instrument durch den Block darunter','Repeater-Richtung und Verzögerung'],install:'INSTALLATION',steps:['Wähle das ZIP für deine Minecraft-Version.','Nicht entpacken. Lege das ZIP in den Ordner resourcepacks.','Aktiviere OTO BLOGIC VISUALS unter Optionen → Ressourcenpakete.'],notes:'KOMPATIBILITÄT',noteItems:['Nur für Java Edition.','In 1.12 werden Tonhöhe und Repeater angezeigt, aber nicht das Instrument.','Klänge von Kreaturenköpfen sind nicht enthalten.'],home:'STARTSEITE',version:'Minecraft Java'},
  zh:{title:'OTO BLOGIC VISUALS',lead:'让 Minecraft 音符盒和红石中继器更容易识别的资源包。',edition:'MINECRAFT JAVA EDITION',choose:'选择你的版本',latest:'最新',download:'下载 ZIP',direct:'直接从 GitHub 下载，不会打开 GitHub 页面。',what:'可以看清什么？',whatText:'直接查看音符盒的音高与乐器，以及中继器的方向与延迟。',features:['音符盒的音高','由下方方块决定的乐器','中继器方向与延迟'],install:'安装方法',steps:['选择与你的 Minecraft 版本相符的 ZIP。','不要解压，将 ZIP 放入 Minecraft 的 resourcepacks 文件夹。','在“选项 → 资源包”中启用 OTO BLOGIC VISUALS。'],notes:'兼容性',noteItems:['仅适用于 Java 版。','1.12 只能显示音高和中继器，不能显示乐器。','不包含生物头颅发出的声音。'],home:'首页',version:'Minecraft Java'},
  'zh-tw':{title:'OTO BLOGIC VISUALS',lead:'讓 Minecraft 音階盒與紅石中繼器更容易辨識的資源包。',edition:'MINECRAFT JAVA EDITION',choose:'選擇你的版本',latest:'最新',download:'下載 ZIP',direct:'直接從 GitHub 下載，不會開啟 GitHub 頁面。',what:'可以看清什麼？',whatText:'直接查看音階盒的音高與樂器，以及中繼器的方向與延遲。',features:['音階盒的音高','由下方方塊決定的樂器','中繼器方向與延遲'],install:'安裝方法',steps:['選擇與你的 Minecraft 版本相符的 ZIP。','不要解壓縮，將 ZIP 放入 Minecraft 的 resourcepacks 資料夾。','在「選項 → 資源包」中啟用 OTO BLOGIC VISUALS。'],notes:'相容性',noteItems:['僅適用於 Java 版。','1.12 只能顯示音高與中繼器，無法顯示樂器。','不包含生物頭顱發出的聲音。'],home:'首頁',version:'Minecraft Java'},
  ko:{title:'OTO BLOGIC VISUALS',lead:'Minecraft 소리 블록과 중계기를 더 쉽게 읽을 수 있게 해 주는 리소스 팩입니다.',edition:'MINECRAFT JAVA EDITION',choose:'버전 선택',latest:'최신',download:'ZIP 다운로드',direct:'GitHub 화면을 열지 않고 바로 다운로드합니다.',what:'무엇을 보여 주나요?',whatText:'소리 블록의 음높이와 악기, 중계기의 방향과 지연을 바로 확인합니다.',features:['소리 블록 음높이','아래 블록으로 결정되는 악기','중계기 방향과 지연'],install:'설치 방법',steps:['Minecraft 버전에 맞는 ZIP을 선택합니다.','압축을 풀지 말고 ZIP을 resourcepacks 폴더에 넣습니다.','설정 → 리소스 팩에서 OTO BLOGIC VISUALS를 활성화합니다.'],notes:'호환성',noteItems:['Java Edition 전용입니다.','1.12에서는 음높이와 중계기만 표시됩니다.','몽 머리에서 나는 소리는 포함하지 않습니다.'],home:'홈',version:'Minecraft Java'},
  id:{title:'OTO BLOGIC VISUALS',lead:'Paket resource agar note block dan repeater Minecraft lebih mudah dibaca.',edition:'MINECRAFT JAVA EDITION',choose:'Pilih versi',latest:'TERBARU',download:'UNDUH ZIP',direct:'Unduh langsung dari GitHub tanpa membuka halaman GitHub.',what:'APA YANG DITAMPILKAN?',whatText:'Lihat nada dan instrumen note block, serta arah dan delay repeater langsung pada blok.',features:['Nada note block','Instrumen dari blok di bawahnya','Arah dan delay repeater'],install:'CARA MEMASANG',steps:['Pilih ZIP yang sesuai dengan versi Minecraft.','Jangan diekstrak. Masukkan ZIP ke folder resourcepacks.','Aktifkan OTO BLOGIC VISUALS di Options → Resource Packs.'],notes:'KOMPATIBILITAS',noteItems:['Khusus Java Edition.','Di 1.12, nada dan repeater terlihat tetapi instrumen tidak.','Suara dari kepala mob tidak termasuk.'],home:'BERANDA',version:'Minecraft Java'},
}

type BedrockCopy={lead:string;edition:string;choose:string;latest:string;download:string;direct:string;what:string;whatText:string;features:string[];install:string;steps:string[];notes:string;noteItems:string[];version:string;captions:[string,string];javaTab:string;bedrockTab:string}
const bedrockCopy:Record<string,BedrockCopy>={
  ja:{lead:'音符ブロックを鳴らしたときのパーティクルを、クリック回数がわかる数字に変えるBedrock版リソースパックです。',edition:'MINECRAFT BEDROCK EDITION',choose:'使っているバージョン',latest:'最新',download:'MCPACKをダウンロード',direct:'Windows・Android・iOSへ直接インポートできるファイルです。',what:'クリック回数を、その場で確認',whatText:'音符ブロックをクリックしたときや演奏中に現れる♪を、1〜23の数字へ置き換えます。数字はパーティクルとして短時間だけ表示されます。',features:['クリック回数1〜23を数字で表示','操作時と演奏中の両方に対応','標準に近い見やすい表示サイズ'],install:'入れ方',steps:['Minecraftに合うMCPACKを選んでダウンロードします。','Windows・Android・iOSでファイルを開き、Minecraftへインポートします。','ワールド設定の「リソースパック」から有効にします。'],notes:'Bedrock版の仕様',noteItems:['クリック回数0と24は同じ色のため区別できず、どちらも標準の「♪」を表示します。','数字は短時間だけ出るパーティクルです。Java版のような常時表示ではありません。','音色用ブロックとリピーターの見た目は変更しません。','Switchへリソースパックを直接インポートすることはできません。'],version:'Minecraft Bedrock',captions:['0と24では、Minecraft標準の「♪」を表示します。','クリック回数1〜23は、音符の色に合わせた数字で表示します。'],javaTab:'JAVA版',bedrockTab:'BEDROCK版'},
  en:{lead:'A Bedrock resource pack that turns note particles into numbers showing the note-block click count.',edition:'MINECRAFT BEDROCK EDITION',choose:'Choose your version',latest:'LATEST',download:'DOWNLOAD MCPACK',direct:'Import directly on Windows, Android, or iOS.',what:'SEE THE CLICK COUNT AS YOU PLAY',whatText:'The particle shown when a note block is tuned or played becomes a number from 1 to 23. It appears briefly, just like the original note particle.',features:['Shows click counts 1–23','Works while tuning and during playback','Readable size close to the original particle'],install:'HOW TO INSTALL',steps:['Choose the MCPACK for your Minecraft version.','Open the file on Windows, Android, or iOS to import it into Minecraft.','Enable it in the world’s Resource Packs settings.'],notes:'BEDROCK EDITION NOTES',noteItems:['Clicks 0 and 24 use the same particle color, so both remain the default “♪”.','Numbers are brief particles, not permanent labels like the Java pack.','Instrument blocks and repeaters keep their default appearance.','Resource packs cannot be imported directly on Nintendo Switch.'],version:'Minecraft Bedrock',captions:['Clicks 0 and 24 keep Minecraft’s default “♪”.','Clicks 1–23 appear as color-matched numbers.'],javaTab:'JAVA EDITION',bedrockTab:'BEDROCK EDITION'},
  es:{lead:'Un pack para Bedrock que convierte las partículas de notas en números con la cantidad de clics.',edition:'MINECRAFT BEDROCK EDITION',choose:'Elige tu versión',latest:'MÁS RECIENTE',download:'DESCARGAR MCPACK',direct:'Importación directa en Windows, Android o iOS.',what:'VE LOS CLICS AL TOCAR',whatText:'La partícula que aparece al afinar o tocar un bloque musical se convierte en un número del 1 al 23 y desaparece al poco tiempo.',features:['Muestra los clics del 1 al 23','Funciona al afinar y durante la reproducción','Tamaño legible similar al original'],install:'INSTALACIÓN',steps:['Elige el MCPACK para tu versión.','Abre el archivo en Windows, Android o iOS para importarlo en Minecraft.','Actívalo en los paquetes de recursos del mundo.'],notes:'NOTAS DE BEDROCK',noteItems:['Los clics 0 y 24 tienen el mismo color y conservan el símbolo “♪”.','Los números son partículas breves, no etiquetas permanentes.','Los bloques de instrumento y repetidores no cambian.','No se puede importar directamente en Nintendo Switch.'],version:'Minecraft Bedrock',captions:['Los clics 0 y 24 conservan el símbolo “♪”.','Los clics 1–23 aparecen como números de color.'],javaTab:'JAVA',bedrockTab:'BEDROCK'},
  fr:{lead:'Un pack Bedrock qui transforme les particules de notes en nombres indiquant le nombre de clics.',edition:'MINECRAFT BEDROCK EDITION',choose:'Choisissez votre version',latest:'RÉCENT',download:'TÉLÉCHARGER LE MCPACK',direct:'Importation directe sur Windows, Android ou iOS.',what:'VOYEZ LE NOMBRE DE CLICS',whatText:'La particule affichée lors du réglage ou de la lecture d’un bloc musical devient un nombre de 1 à 23 et disparaît rapidement.',features:['Affiche les clics de 1 à 23','Fonctionne au réglage et à la lecture','Taille lisible proche de l’original'],install:'INSTALLATION',steps:['Choisissez le MCPACK adapté à votre version.','Ouvrez-le sur Windows, Android ou iOS pour l’importer dans Minecraft.','Activez-le dans les packs de ressources du monde.'],notes:'REMARQUES BEDROCK',noteItems:['Les clics 0 et 24 ont la même couleur et gardent le symbole « ♪ ».','Les nombres sont des particules brèves, pas des étiquettes permanentes.','Les blocs d’instrument et les répéteurs restent inchangés.','L’importation directe est impossible sur Nintendo Switch.'],version:'Minecraft Bedrock',captions:['Les clics 0 et 24 gardent le symbole « ♪ ».','Les clics 1 à 23 apparaissent sous forme de nombres colorés.'],javaTab:'JAVA',bedrockTab:'BEDROCK'},
  de:{lead:'Ein Bedrock-Ressourcenpaket, das Notenpartikel in Zahlen für die Klickanzahl umwandelt.',edition:'MINECRAFT BEDROCK EDITION',choose:'Version auswählen',latest:'NEUESTE',download:'MCPACK HERUNTERLADEN',direct:'Direkter Import unter Windows, Android oder iOS.',what:'KLICKANZAHL BEIM SPIELEN SEHEN',whatText:'Beim Stimmen oder Abspielen eines Notenblocks erscheint kurz eine Zahl von 1 bis 23 anstelle des Notenpartikels.',features:['Zeigt Klicks 1–23','Beim Stimmen und Abspielen','Gut lesbare Originalgröße'],install:'INSTALLATION',steps:['Wähle das MCPACK für deine Version.','Öffne die Datei unter Windows, Android oder iOS, um sie zu importieren.','Aktiviere sie in den Ressourcenpaketen der Welt.'],notes:'BEDROCK-HINWEISE',noteItems:['Klicks 0 und 24 haben dieselbe Farbe und bleiben daher als „♪“.','Zahlen sind kurze Partikel, keine dauerhaften Beschriftungen.','Instrumentblöcke und Repeater bleiben unverändert.','Auf Nintendo Switch ist kein direkter Import möglich.'],version:'Minecraft Bedrock',captions:['Klicks 0 und 24 zeigen weiterhin „♪“.','Klicks 1–23 erscheinen als farbige Zahlen.'],javaTab:'JAVA',bedrockTab:'BEDROCK'},
  zh:{lead:'将音符盒粒子替换为点击次数数字的基岩版资源包。',edition:'MINECRAFT BEDROCK EDITION',choose:'选择你的版本',latest:'最新',download:'下载 MCPACK',direct:'可在 Windows、Android 或 iOS 直接导入。',what:'演奏时查看点击次数',whatText:'调音或播放音符盒时出现的粒子会变成1至23的数字，并像原版音符粒子一样短暂显示。',features:['显示1至23次点击','调音与播放时均有效','显示大小接近原版'],install:'安装方法',steps:['选择与你的版本相符的MCPACK。','在Windows、Android或iOS打开文件并导入Minecraft。','在世界的“资源包”设置中启用。'],notes:'基岩版说明',noteItems:['0和24次点击的粒子颜色相同，因此都保留“♪”。','数字是短暂粒子，不会像Java版一样常驻。','乐器方块和中继器外观不变。','Nintendo Switch无法直接导入资源包。'],version:'Minecraft Bedrock',captions:['0和24次点击保留原版“♪”。','1至23次点击显示为对应颜色的数字。'],javaTab:'JAVA版',bedrockTab:'基岩版'},
  'zh-tw':{lead:'將音階盒粒子替換為點擊次數數字的基岩版資源包。',edition:'MINECRAFT BEDROCK EDITION',choose:'選擇你的版本',latest:'最新',download:'下載 MCPACK',direct:'可在 Windows、Android 或 iOS 直接匯入。',what:'演奏時查看點擊次數',whatText:'調音或播放音階盒時出現的粒子會變成1至23的數字，並像原版音符粒子一樣短暫顯示。',features:['顯示1至23次點擊','調音與播放時均有效','顯示大小接近原版'],install:'安裝方法',steps:['選擇與你的版本相符的MCPACK。','在Windows、Android或iOS開啟檔案並匯入Minecraft。','在世界的「資源包」設定中啟用。'],notes:'基岩版說明',noteItems:['0和24次點擊的粒子顏色相同，因此都保留「♪」。','數字是短暫粒子，不會像Java版一樣常駐。','樂器方塊和中繼器外觀不變。','Nintendo Switch無法直接匯入資源包。'],version:'Minecraft Bedrock',captions:['0和24次點擊保留原版「♪」。','1至23次點擊顯示為對應顏色的數字。'],javaTab:'JAVA版',bedrockTab:'基岩版'},
  ko:{lead:'음표 입자를 소리 블록 클릭 횟수 숫자로 바꾸는 Bedrock 리소스 팩입니다.',edition:'MINECRAFT BEDROCK EDITION',choose:'버전 선택',latest:'최신',download:'MCPACK 다운로드',direct:'Windows, Android 또는 iOS에서 바로 가져올 수 있습니다.',what:'연주 중 클릭 횟수 확인',whatText:'소리 블록을 조율하거나 재생할 때 나오는 입자가 1~23 숫자로 바뀌며 잠시 표시됩니다.',features:['클릭 횟수 1~23 표시','조율과 재생 모두 지원','원본과 비슷한 가독성 좋은 크기'],install:'설치 방법',steps:['버전에 맞는 MCPACK을 선택합니다.','Windows, Android 또는 iOS에서 파일을 열어 Minecraft로 가져옵니다.','월드의 리소스 팩 설정에서 활성화합니다.'],notes:'BEDROCK 안내',noteItems:['0과 24는 입자 색이 같아 둘 다 기본 “♪”로 표시됩니다.','숫자는 잠깐 나타나는 입자이며 항상 표시되지 않습니다.','악기 블록과 중계기 모양은 바뀌지 않습니다.','Nintendo Switch에는 직접 가져올 수 없습니다.'],version:'Minecraft Bedrock',captions:['0과 24는 기본 “♪”를 표시합니다.','1~23은 색상에 맞는 숫자로 표시됩니다.'],javaTab:'JAVA',bedrockTab:'BEDROCK'},
  id:{lead:'Paket Bedrock yang mengubah partikel not menjadi angka jumlah klik note block.',edition:'MINECRAFT BEDROCK EDITION',choose:'Pilih versi',latest:'TERBARU',download:'UNDUH MCPACK',direct:'Impor langsung di Windows, Android, atau iOS.',what:'LIHAT JUMLAH KLIK SAAT BERMAIN',whatText:'Partikel saat menyetel atau memainkan note block berubah menjadi angka 1–23 dan tampil sesaat.',features:['Menampilkan klik 1–23','Aktif saat menyetel dan memainkan','Ukuran mudah dibaca seperti partikel asli'],install:'CARA MEMASANG',steps:['Pilih MCPACK untuk versi Minecraft Anda.','Buka file di Windows, Android, atau iOS untuk mengimpornya.','Aktifkan di Resource Packs dunia.'],notes:'CATATAN BEDROCK',noteItems:['Klik 0 dan 24 memiliki warna sama sehingga tetap tampil sebagai “♪”.','Angka hanya partikel singkat, bukan label permanen.','Blok instrumen dan repeater tidak berubah.','Nintendo Switch tidak mendukung impor langsung.'],version:'Minecraft Bedrock',captions:['Klik 0 dan 24 tetap menampilkan “♪”.','Klik 1–23 tampil sebagai angka berwarna.'],javaTab:'JAVA',bedrockTab:'BEDROCK'},
}

const downloadBase='https://raw.githubusercontent.com/SOTA56/OTO_BLOGIC_VISUALS/main/dist/'
const previewCopy:Record<string,string>={
  ja:'音符ブロックの音程と音の種類、リピーターの向きと遅延をゲーム内で確認できます。Minecraft Java版専用です。',
  en:'Read note-block pitches and sound types, plus repeater direction and delay, directly in the game. For Minecraft Java Edition only.',
  es:'Consulta las notas, los tipos de sonido y los ajustes del repetidor directamente en el juego. Solo para Minecraft Java Edition.',
  fr:'Repérez les hauteurs, les types de son et les réglages des répéteurs directement dans le jeu. Uniquement pour Minecraft Java Edition.',
  de:'Erkenne Tonhöhen, Klangarten und Repeater-Einstellungen direkt im Spiel. Nur für Minecraft Java Edition.',
  zh:'直接在游戏中查看音符盒的音高、声音种类和中继器设置。仅适用于 Minecraft Java 版。',
  'zh-tw':'直接在遊戲中查看音階盒的音高、聲音種類與中繼器設定。僅適用於 Minecraft Java 版。',
  ko:'게임 안에서 소리 블록의 음높이와 소리 종류, 중계기 설정을 확인할 수 있습니다. Minecraft Java Edition 전용입니다.',
  id:'Lihat nada, jenis suara, serta arah dan delay repeater langsung di dalam game. Khusus Minecraft Java Edition.',
}

export default function ResourcePackPage({language,setLanguage,onHome}:Props){
  const t=copy[language]??copy.en
  const bt=bedrockCopy[language]??bedrockCopy.en
  const [edition,setEdition]=useState<'java'|'bedrock'>('java')
  const [selectedFile,setSelectedFile]=useState<string>(packs[0].file)
  const [selectedBedrockFile,setSelectedBedrockFile]=useState<string>(bedrockPacks[0].file)
  const selected=packs.find(pack=>pack.file===selectedFile)??packs[0]
  const selectedBedrock=bedrockPacks.find(pack=>pack.file===selectedBedrockFile)??bedrockPacks[0]
  const isBedrock=edition==='bedrock'
  return <main className="resource-pack-page">
    <BuyMeCoffeeWidget/>
    <header className="resource-pack-header">
      <button className="resource-pack-brand" onClick={onHome} aria-label={t.home}><img src="/assets/branding/oto-blogic-icon-04.png" alt=""/><img src="/assets/branding/oto-blogic-logo.png" alt="OTO BLOGIC"/></button>
      <div><button className="resource-pack-home" onClick={onHome}>← {t.home}</button><select className="resource-pack-language" value={language} onChange={event=>setLanguage(event.target.value)} aria-label="Language">{languageOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div>
    </header>
    <nav className="resource-pack-edition-tabs" aria-label="Minecraft edition">
      <button className={edition==='java'?'active':''} onClick={()=>setEdition('java')} aria-pressed={edition==='java'}><span>JAVA</span><small>{bt.javaTab}</small></button>
      <button className={edition==='bedrock'?'active bedrock':''} onClick={()=>setEdition('bedrock')} aria-pressed={edition==='bedrock'}><span>BEDROCK</span><small>{bt.bedrockTab}</small></button>
    </nav>
    <section className="resource-pack-hero">
      <small>OFFICIAL RESOURCE PACK</small><h1>{t.title}</h1><p>{isBedrock?bt.lead:t.lead}</p><b>{isBedrock?bt.edition:t.edition}</b>
    </section>
    <div className="resource-pack-content">
      <section className="resource-pack-download">
        <div className="resource-pack-number">01</div><div><h2>{isBedrock?bt.choose:t.choose}</h2>{isBedrock?<label><span>{bt.version}</span><select value={selectedBedrockFile} onChange={event=>setSelectedBedrockFile(event.target.value)}>{bedrockPacks.map(pack=><option value={pack.file} key={pack.file}>{pack.version}{pack.latest?` — ${bt.latest}`:''}</option>)}</select></label>:<label><span>{t.version}</span><select value={selectedFile} onChange={event=>setSelectedFile(event.target.value)}>{packs.map(pack=><option value={pack.file} key={pack.file}>{pack.version}{pack.latest?` — ${t.latest}`:''}</option>)}</select></label>}<a href={isBedrock?`/downloads/${selectedBedrock.file}`:`${downloadBase}${selected.file}`} download={isBedrock?selectedBedrock.file:selected.file} className={`resource-pack-download-button ${isBedrock?'bedrock':''}`} aria-label={`${isBedrock?bt.download:t.download} — ${isBedrock?`Minecraft Bedrock ${selectedBedrock.version}`:`Minecraft Java ${selected.version}`}`}><span>{isBedrock?bt.download:t.download}</span><b>⇩</b></a><p className="resource-pack-download-note">{isBedrock?bt.direct:t.direct}</p></div>
      </section>
      <section className="resource-pack-explainer"><div><small>{isBedrock?'READ THE PARTICLE':'READ THE CIRCUIT'}</small><h2>{isBedrock?bt.what:t.what}</h2><p>{isBedrock?bt.whatText:t.whatText}</p></div><ol>{(isBedrock?bt.features:t.features).map((feature,index)=><li key={feature}><b>{String(index+1).padStart(2,'0')}</b><span>{feature}</span></li>)}</ol>{isBedrock?<div className="resource-pack-preview-grid"><figure className="resource-pack-preview"><img src="/assets/resource-pack/bedrock-note-digits.jpg" alt="OTO BLOGIC VISUALS showing click-count particles in Minecraft Bedrock Edition"/><figcaption>{bt.captions[1]}</figcaption></figure><figure className="resource-pack-preview"><img src="/assets/resource-pack/bedrock-default-note.jpg" alt="Minecraft Bedrock Edition showing the default note particle for click counts 0 and 24"/><figcaption>{bt.captions[0]}</figcaption></figure></div>:<figure className="resource-pack-preview"><img src="/assets/resource-pack/visuals-in-game.jpg" alt="OTO BLOGIC VISUALS in Minecraft Java Edition"/><figcaption>{previewCopy[language]??previewCopy.en}</figcaption></figure>}</section>
      <section className={`resource-pack-install ${isBedrock?'bedrock':''}`}><header><small>THREE STEPS</small><h2>{isBedrock?bt.install:t.install}</h2></header><ol>{(isBedrock?bt.steps:t.steps).map((step,index)=><li key={step}><b>{index+1}</b><p>{step}</p></li>)}</ol></section>
      <section className="resource-pack-notes"><h2>{isBedrock?bt.notes:t.notes}</h2><ul>{(isBedrock?bt.noteItems:t.noteItems).map(item=><li key={item}>{item}</li>)}</ul></section>
    </div>
    <footer className="resource-pack-footer"><button onClick={onHome}>← {t.home}</button><span>© 2026 OTO BLOGIC · Powered by SOTA56</span></footer>
  </main>
}
